//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlMetal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinqToSqlShared_DbmlObjectModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinqToSqlShared_DbmlObjectModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calysto.SqlMetal.SqlMetal.Resources.LinqToSqlShared.DbmlObjectModel", typeof(LinqToSqlShared_DbmlObjectModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUG {0}.
        /// </summary>
        internal static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1113: Database node not found.  Is the DBML namespace ({0}) correctly specified?.
        /// </summary>
        internal static string DatabaseNodeNotFound {
            get {
                return ResourceManager.GetString("DatabaseNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1108: Element {0} must only appear at most once..
        /// </summary>
        internal static string ElementMoreThanOnceViolation {
            get {
                return ResourceManager.GetString("ElementMoreThanOnceViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1105: The boolean attribute value &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidBooleanAttributeValueViolation {
            get {
                return ResourceManager.GetString("InvalidBooleanAttributeValueViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1106: The value &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidEnumAttributeValueViolation {
            get {
                return ResourceManager.GetString("InvalidEnumAttributeValueViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLinq.
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1109: Required attribute {0} is missing..
        /// </summary>
        internal static string RequiredAttributeMissingViolation {
            get {
                return ResourceManager.GetString("RequiredAttributeMissingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1107: Element {0} is required..
        /// </summary>
        internal static string RequiredElementMissingViolation {
            get {
                return ResourceManager.GetString("RequiredElementMissingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1100: Duplicate {0} seen with value &apos;{1}&apos;..
        /// </summary>
        internal static string SchemaDuplicateIdViolation {
            get {
                return ResourceManager.GetString("SchemaDuplicateIdViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1112: Element &apos;{0}&apos; must be empty, but contains a node of type {1} named &apos;{2}&apos;..
        /// </summary>
        internal static string SchemaExpectedEmptyElement {
            get {
                return ResourceManager.GetString("SchemaExpectedEmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1101: Unresolved reference {0} {1}: &apos;{2}&apos;..
        /// </summary>
        internal static string SchemaInvalidIdRefToNonexistentId {
            get {
                return ResourceManager.GetString("SchemaInvalidIdRefToNonexistentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1102: {0} requires {1} or {2}..
        /// </summary>
        internal static string SchemaOrRequirementViolation {
            get {
                return ResourceManager.GetString("SchemaOrRequirementViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1110: The type IdRef &apos;{0}&apos; cannot point to the type &apos;{1}&apos; because it is in the same inheritance hierarchy..
        /// </summary>
        internal static string SchemaRecursiveTypeReference {
            get {
                return ResourceManager.GetString("SchemaRecursiveTypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires {1}..
        /// </summary>
        internal static string SchemaRequirementViolation {
            get {
                return ResourceManager.GetString("SchemaRequirementViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1104: Attribute {0} on element {1} must appear alone..
        /// </summary>
        internal static string SchemaUnexpectedAdditionalAttributeViolation {
            get {
                return ResourceManager.GetString("SchemaUnexpectedAdditionalAttributeViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1103: Element {0} is unexpected under {1} element..
        /// </summary>
        internal static string SchemaUnexpectedElementViolation {
            get {
                return ResourceManager.GetString("SchemaUnexpectedElementViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1111: Unrecognized attribute &apos;{0}&apos; in file..
        /// </summary>
        internal static string SchemaUnrecognizedAttribute {
            get {
                return ResourceManager.GetString("SchemaUnrecognizedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1114: The Name attribute &apos;{0}&apos; of the Type element is already used by another type..
        /// </summary>
        internal static string TypeNameNotUnique {
            get {
                return ResourceManager.GetString("TypeNameNotUnique", resourceCulture);
            }
        }
    }
}
