//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlMetal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinqToSqlShared_Generator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinqToSqlShared_Generator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calysto.SqlMetal.SqlMetal.Resources.LinqToSqlShared.Generator", typeof(LinqToSqlShared_Generator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1003: The Modifier attribute of the Type element &apos;{0}&apos; cannot be Abstract when it has InheritanceCode..
        /// </summary>
        internal static string AbstractTypeHasInheritanceCode {
            get {
                return ResourceManager.GetString("AbstractTypeHasInheritanceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1059: The IsForeignKey attribute of the Association element &apos;{0}&apos; of the Type element &apos;{1}&apos; cannot be &apos;True&apos; when the Cardinality attribute is &apos;Many&apos;..
        /// </summary>
        internal static string AssociationManysideIsForeignKey {
            get {
                return ResourceManager.GetString("AssociationManysideIsForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1013: Attribute &apos;{0}&apos; is not present in {1} &apos;{2}&apos; of the {3} element &apos;{4}&apos;..
        /// </summary>
        internal static string AttributeIsNotPresent {
            get {
                return ResourceManager.GetString("AttributeIsNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1012: The Column member &apos;{0}&apos; does not exist in the Type element &apos;{1}&apos;..
        /// </summary>
        internal static string ColumnMemberDoesNotExist {
            get {
                return ResourceManager.GetString("ColumnMemberDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1068: Passwords stored in the connection string are written in clear text in the generated code file and the final application assembly. Whenever possible, use Windows Integrated Security to connect so that a password is not required in the connection string..
        /// </summary>
        internal static string ConnectionStringTransferredToCode {
            get {
                return ResourceManager.GetString("ConnectionStringTransferredToCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to make property name from association {0}..
        /// </summary>
        internal static string CouldNotMakePropertyNameForAssociation {
            get {
                return ResourceManager.GetString("CouldNotMakePropertyNameForAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to make unique table name from &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotMakeUniqueTableName {
            get {
                return ResourceManager.GetString("CouldNotMakeUniqueTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to make unique variable name from &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotMakeUniqueVariableName {
            get {
                return ResourceManager.GetString("CouldNotMakeUniqueVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1009: Mapping between DbType &apos;{0}&apos; and Type &apos;{1}&apos; in {2} &apos;{3}&apos; of {4} &apos;{5}&apos; may cause data loss when saving to and loading from the database..
        /// </summary>
        internal static string DataLossBoth {
            get {
                return ResourceManager.GetString("DataLossBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1008: Mapping between DbType &apos;{0}&apos; and Type &apos;{1}&apos; in {2} &apos;{3}&apos; of {4} &apos;{5}&apos; may cause data loss when loading from the database..
        /// </summary>
        internal static string DataLossFromDatabase {
            get {
                return ResourceManager.GetString("DataLossFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1007: Mapping between DbType &apos;{0}&apos; and Type &apos;{1}&apos; in {2} &apos;{3}&apos; of {4} &apos;{5}&apos; may cause data loss when saving to the database..
        /// </summary>
        internal static string DataLossToDatabase {
            get {
                return ResourceManager.GetString("DataLossToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensibility Method Definitions.
        /// </summary>
        internal static string ExtensibilityMethodDefinitions {
            get {
                return ResourceManager.GetString("ExtensibilityMethodDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1019: The Type element &apos;{0}&apos; must have an InheritanceCode when its Column element &apos;{1}&apos; is a discriminator..
        /// </summary>
        internal static string InheritanceCodeMissingWhenHaveDiscriminator {
            get {
                return ResourceManager.GetString("InheritanceCodeMissingWhenHaveDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1034: The Member attribute &apos;{0}&apos; is not a valid identifier in the Association element of the Type element &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidAssociationMemberIdentifier {
            get {
                return ResourceManager.GetString("InvalidAssociationMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1033: The Member attribute &apos;{0}&apos; is not a valid identifier in the Column element of the Type element &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidColumnMemberIdentifier {
            get {
                return ResourceManager.GetString("InvalidColumnMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1000: ContextNamespace &apos;{0}&apos; is invalid in the Database element &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidContextNameSpace {
            get {
                return ResourceManager.GetString("InvalidContextNameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1030: The Class attribute &apos;{0}&apos; is not a valid identifier in the Database element..
        /// </summary>
        internal static string InvalidDatabaseClassIdentifier {
            get {
                return ResourceManager.GetString("InvalidDatabaseClassIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1052: The Name &apos;{0}&apos; of the Column element of the Type element &apos;{1}&apos; must be a valid variable name when the Member attribute is not present..
        /// </summary>
        internal static string InvalidDefaultColumnMemberIdentifier {
            get {
                return ResourceManager.GetString("InvalidDefaultColumnMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1050: The Name &apos;{0}&apos; of the Database element must be a valid variable name when the Class attribute is not present..
        /// </summary>
        internal static string InvalidDefaultDatabaseClassIdentifier {
            get {
                return ResourceManager.GetString("InvalidDefaultDatabaseClassIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1053: The Name &apos;{0}&apos; of the Function element must be a valid variable name when the Method attribute is not present..
        /// </summary>
        internal static string InvalidDefaultFunctionMethodIdentifier {
            get {
                return ResourceManager.GetString("InvalidDefaultFunctionMethodIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1054: The Name &apos;{0}&apos; of the Parameter element must be a valid variable name when the Parameter attribute is not present..
        /// </summary>
        internal static string InvalidDefaultParameterParameterIdentifier {
            get {
                return ResourceManager.GetString("InvalidDefaultParameterParameterIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1051: The Name &apos;{0}&apos; of the Table element must be a valid variable name when the Member attribute is not present..
        /// </summary>
        internal static string InvalidDefaultTableMemberIdentifier {
            get {
                return ResourceManager.GetString("InvalidDefaultTableMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1055: The DeleteOnNull attribute of the Association element &apos;{0}&apos; of the Type element &apos;{1}&apos; can only be true for singleton association members mapped to non-nullable foreign key columns..
        /// </summary>
        internal static string InvalidDeleteOnNullSpecification {
            get {
                return ResourceManager.GetString("InvalidDeleteOnNullSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1001: EntityNamespace &apos;{0}&apos; is invalid in the Database element &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidEntityNameSpace {
            get {
                return ResourceManager.GetString("InvalidEntityNameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1035: The Method attribute &apos;{0}&apos; is not a valid identifier in the Function element..
        /// </summary>
        internal static string InvalidFunctionMethodIdentifier {
            get {
                return ResourceManager.GetString("InvalidFunctionMethodIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1063: The Column element &apos;{0}&apos; of the Type element &apos;{1}&apos; cannot be used as an identity because &apos;{2}&apos; is not a supported {3} for identity members..
        /// </summary>
        internal static string InvalidIdentityMememberType {
            get {
                return ResourceManager.GetString("InvalidIdentityMememberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1032: The Name attribute &apos;{0}&apos; is not a valid identifier in the Type element..
        /// </summary>
        internal static string InvalidITypeNamedentifier {
            get {
                return ResourceManager.GetString("InvalidITypeNamedentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1036: The Parameter attribute &apos;{0}&apos; is not a valid identifier in the Parameter element..
        /// </summary>
        internal static string InvalidParameterParameterIdentifier {
            get {
                return ResourceManager.GetString("InvalidParameterParameterIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1031: The Member attribute &apos;{0}&apos; is not a valid identifier in the Table element..
        /// </summary>
        internal static string InvalidTableMemberIdentifier {
            get {
                return ResourceManager.GetString("InvalidTableMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1049: The value of IsComposable and the value of HasMultipleResults do not match in the Function element &apos;{0}&apos;..
        /// </summary>
        internal static string IsComposableAndHasMultipleResultsDoNotMatch {
            get {
                return ResourceManager.GetString("IsComposableAndHasMultipleResultsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1048: The value of IsComposable and the number of return types do not match in the Function element &apos;{0}&apos;..
        /// </summary>
        internal static string IsComposableAndNumberOfTypeDoNotMatch {
            get {
                return ResourceManager.GetString("IsComposableAndNumberOfTypeDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1064: CUD overrides are not supported in the keyless table &apos;{0}&apos;..
        /// </summary>
        internal static string KeylessTablesCannotHaveCUDOverrides {
            get {
                return ResourceManager.GetString("KeylessTablesCannotHaveCUDOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1021: The Member attribute of the {0} element &apos;{1}&apos; must be different from the name of the Type element &apos;{2}&apos;..
        /// </summary>
        internal static string MemberCannotBeTheSameAsTypeName {
            get {
                return ResourceManager.GetString("MemberCannotBeTheSameAsTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThisKey column member &apos;{0}&apos; in association of table &apos;{1}&apos; and key member &apos;{2}&apos; in type &apos;{3}&apos; do not match..
        /// </summary>
        internal static string MismatchedThisKeyOtherKey {
            get {
                return ResourceManager.GetString("MismatchedThisKeyOtherKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1016: IsDiscriminator cannot be True in the Column element &apos;{0}&apos; of the Type element &apos;{1}&apos; because there is already a discriminator column in the inheritance hierarchy..
        /// </summary>
        internal static string MultipleDiscriminators {
            get {
                return ResourceManager.GetString("MultipleDiscriminators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1015: IsInheritanceDefault cannot be True in the Type element &apos;{0}&apos; because there is already an inheritance default type in the inheritance hierarchy..
        /// </summary>
        internal static string MultipleInheritanceDefaultTypes {
            get {
                return ResourceManager.GetString("MultipleInheritanceDefaultTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1018: The Table element &apos;{0}&apos; must contain a Column element that has IsDiscriminator set to true in the inheritance hierarchy..
        /// </summary>
        internal static string NoDiscriminator {
            get {
                return ResourceManager.GetString("NoDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1004: The Type element &apos;{0}&apos; must have InheritanceCode when the InheritanceDefault attribute is True..
        /// </summary>
        internal static string NoInheritanceCodeWhenIsInheritanceDefault {
            get {
                return ResourceManager.GetString("NoInheritanceCodeWhenIsInheritanceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1017: The Table element &apos;{0}&apos; must contain a type that has IsInheritanceDefault set to true in the inheritance hierarchy..
        /// </summary>
        internal static string NoInheritanceDefaultTypes {
            get {
                return ResourceManager.GetString("NoInheritanceDefaultTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1002: ThisKey and OtherKey are required in the Association element &apos;{0}&apos; of the Type element &apos;{1}..
        /// </summary>
        internal static string NoKeysSpecifiedInAssociation {
            get {
                return ResourceManager.GetString("NoKeysSpecifiedInAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1020: The Type element &apos;{0}&apos; is not a a table type in the database..
        /// </summary>
        internal static string NotTableType {
            get {
                return ResourceManager.GetString("NotTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1062: The Type attribute &apos;{0}&apos; of the Association element &apos;{1}&apos; of the Type element &apos;{2}&apos; does not have a primary key.  No code will be generated for the association..
        /// </summary>
        internal static string OtherSideHasNoPrimaryKey {
            get {
                return ResourceManager.GetString("OtherSideHasNoPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLinq.
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1056: There is no Parameter &apos;{0}&apos; in the Function element &apos;{1}&apos; corresponding to the Argument &apos;{2}&apos; of the TableFunction..
        /// </summary>
        internal static string ParameterDoesNotExistInFunction {
            get {
                return ResourceManager.GetString("ParameterDoesNotExistInFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1060: The AutoSync attribute of the Column element &apos;{0}&apos; of the Type element &apos;{1}&apos; needs to be &apos;OnInsert&apos; when IsDbGenerated and IsPrimaryKey are &apos;True&apos;..
        /// </summary>
        internal static string PrimaryKeyAutoSyncNeedsToBeOnInsertWhenIsDbGenerated {
            get {
                return ResourceManager.GetString("PrimaryKeyAutoSyncNeedsToBeOnInsertWhenIsDbGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1061: The AutoSync attribute of the Column element &apos;{0}&apos; of the Type element &apos;{1}&apos; needs to be &apos;OnInsert&apos; when IsVersion and IsPrimaryKey are &apos;True&apos;..
        /// </summary>
        internal static string PrimaryKeyAutoSyncNeedsToBeOnInsertWhenIsVersion {
            get {
                return ResourceManager.GetString("PrimaryKeyAutoSyncNeedsToBeOnInsertWhenIsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1027: Mapping between DbType &apos;{0}&apos; and Type &apos;{1}&apos; in the Return element of the {2} element &apos;{3}&apos; may cause data loss when saving to and loading from the database..
        /// </summary>
        internal static string ReturnDataLossBoth {
            get {
                return ResourceManager.GetString("ReturnDataLossBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1026: Mapping between DbType &apos;{0}&apos; and Type &apos;{1}&apos; in the Return element of the {2} element &apos;{3}&apos; may cause data loss when loading from the database..
        /// </summary>
        internal static string ReturnDataLossFromDatabase {
            get {
                return ResourceManager.GetString("ReturnDataLossFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1025: Mapping between DbType &apos;{0}&apos; and Type &apos;{1}&apos; in the Return element of the {2} element &apos;{3}&apos; may cause data loss when saving to the database..
        /// </summary>
        internal static string ReturnDataLossToDatabase {
            get {
                return ResourceManager.GetString("ReturnDataLossToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1023: Mapping between DbType &apos;{0}&apos; and Type &apos;{1}&apos; in the Return element of the {2} element &apos;{3}&apos; is not supported..
        /// </summary>
        internal static string ReturnTypeMappingNotSupported {
            get {
                return ResourceManager.GetString("ReturnTypeMappingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1029: Unknown CLR type &apos;{0}&apos; is used in the Return element of the {1} element &apos;{2}&apos;..
        /// </summary>
        internal static string ReturnUnknownCLRType {
            get {
                return ResourceManager.GetString("ReturnUnknownCLRType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1024: Unknown DbType &apos;{0}&apos; is used in the Return element of the {1} element &apos;{2}&apos;..
        /// </summary>
        internal static string ReturnUnknownDbType {
            get {
                return ResourceManager.GetString("ReturnUnknownDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1043: The Member attribute &apos;{0}&apos; in the Association element of the Type element &apos;{1}&apos; has been used already..
        /// </summary>
        internal static string SameAssociationMemberIdentifier {
            get {
                return ResourceManager.GetString("SameAssociationMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1042: The Member attribute &apos;{0}&apos; in the Column element of the Type element &apos;{1}&apos; has been used already..
        /// </summary>
        internal static string SameColumnMemberIdentifier {
            get {
                return ResourceManager.GetString("SameColumnMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1041: The Name attribute &apos;{0}&apos; in the Column element of the Type element &apos;{1}&apos; has been used already..
        /// </summary>
        internal static string SameColumnNameIdentifier {
            get {
                return ResourceManager.GetString("SameColumnNameIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1057: The Storage attribute or its default value &apos;{0}&apos; in the Column element of the Type element &apos;{1}&apos; has been used already..
        /// </summary>
        internal static string SameColumnStorageIdentifier {
            get {
                return ResourceManager.GetString("SameColumnStorageIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1045: The Method attribute &apos;{0}&apos; in the Function element has been used already..
        /// </summary>
        internal static string SameFunctionMethodIdentifier {
            get {
                return ResourceManager.GetString("SameFunctionMethodIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1044: The Name attribute &apos;{0}&apos; in the Function element has been used already..
        /// </summary>
        internal static string SameFunctionNameIdentifier {
            get {
                return ResourceManager.GetString("SameFunctionNameIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1046: The Name attribute &apos;{0}&apos; in the Parameter element has been used already..
        /// </summary>
        internal static string SameParameterNameIdentifier {
            get {
                return ResourceManager.GetString("SameParameterNameIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1047: The Parameter attribute &apos;{0}&apos; in the Parameter element has been used already..
        /// </summary>
        internal static string SameParameterParameterIdentifier {
            get {
                return ResourceManager.GetString("SameParameterParameterIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1038: The Member attribute &apos;{0}&apos; in the Table element has been used already..
        /// </summary>
        internal static string SameTableMemberIdentifier {
            get {
                return ResourceManager.GetString("SameTableMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1037: The Table element &apos;{0}&apos; has been used already. Mapping multiple classes to the same table may lead to runtime errors..
        /// </summary>
        internal static string SameTableNameIdentifier {
            get {
                return ResourceManager.GetString("SameTableNameIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1040: The InheritanceCode attribute &apos;{0}&apos; in the Type element &apos;{1}&apos; has been used already..
        /// </summary>
        internal static string SameTypeInheritanceCodeIdentifier {
            get {
                return ResourceManager.GetString("SameTypeInheritanceCodeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1039: The Name attribute &apos;{0}&apos; in the Type element has been used already..
        /// </summary>
        internal static string SameTypeNameIdentifier {
            get {
                return ResourceManager.GetString("SameTypeNameIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1058: The Storage attribute or its default value for the {0} element &apos;{1}&apos; must be different from the name of the Type element &apos;{2}&apos;..
        /// </summary>
        internal static string StorageCannotBeTheSameAsTypeName {
            get {
                return ResourceManager.GetString("StorageCannotBeTheSameAsTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1066: The type element &apos;{0}&apos; is a subtype and cannot contain the primary key column &apos;{1}&apos;..
        /// </summary>
        internal static string SubTypesCannotContainPK {
            get {
                return ResourceManager.GetString("SubTypesCannotContainPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1022: The Method attribute &apos;{0}&apos; of the Function element is already used as the Member attribute of a Table element..
        /// </summary>
        internal static string TableMemberAndMethodConflict {
            get {
                return ResourceManager.GetString("TableMemberAndMethodConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1010: ThisKey and OtherKey do not contain the same number of columns in the Association element &apos;{0}&apos; of the Type element &apos;{1}&apos;..
        /// </summary>
        internal static string ThisKeyOtherKey {
            get {
                return ResourceManager.GetString("ThisKeyOtherKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more unnamed columns in result set..
        /// </summary>
        internal static string TwoOrMoreUnnamedColumnsInResultSet {
            get {
                return ResourceManager.GetString("TwoOrMoreUnnamedColumnsInResultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1011: The Type element &apos;{0}&apos; contains the Association element &apos;{1}&apos; but does not have a primary key.  No code will be generated for the association..
        /// </summary>
        internal static string TypeHasNoPrimaryKey {
            get {
                return ResourceManager.GetString("TypeHasNoPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1005: Mapping between DbType &apos;{0}&apos; and Type &apos;{1}&apos; in {2} &apos;{3}&apos; of {4} &apos;{5}&apos; is not supported..
        /// </summary>
        internal static string TypeMappingNotSupported {
            get {
                return ResourceManager.GetString("TypeMappingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1067: The type element name &apos;{0}&apos; is reserved and cannot be used by a user type..
        /// </summary>
        internal static string TypeNameIsReserved {
            get {
                return ResourceManager.GetString("TypeNameIsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1014: The Column element &apos;{0}&apos; of the Type element &apos;{1}&apos; cannot be used as a discriminator because its {2} is &apos;{3}&apos;..
        /// </summary>
        internal static string TypeNotForDiscriminator {
            get {
                return ResourceManager.GetString("TypeNotForDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract function &apos;{0}&apos;. Exception: {1}.
        /// </summary>
        internal static string UnableToExtractFunction {
            get {
                return ResourceManager.GetString("UnableToExtractFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract stored procedure &apos;{0}&apos;. Exception: {1}.
        /// </summary>
        internal static string UnableToExtractSproc {
            get {
                return ResourceManager.GetString("UnableToExtractSproc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract table &apos;{0}&apos;. Exception: {1}.
        /// </summary>
        internal static string UnableToExtractTable {
            get {
                return ResourceManager.GetString("UnableToExtractTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract view &apos;{0}&apos;. Exception: {1}.
        /// </summary>
        internal static string UnableToExtractView {
            get {
                return ResourceManager.GetString("UnableToExtractView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1028: Unknown CLR type &apos;{0}&apos; is used in {1} &apos;{2}&apos; of the {3} element &apos;{4}&apos;..
        /// </summary>
        internal static string UnknownCLRType {
            get {
                return ResourceManager.GetString("UnknownCLRType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1006: Unknown DbType &apos;{0}&apos; is used in {1} &apos;{2}&apos; of {3} &apos;{4}&apos;..
        /// </summary>
        internal static string UnknownDbType {
            get {
                return ResourceManager.GetString("UnknownDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML1065: User defined DbType &apos;{0}&apos; is used in {1} &apos;{2}&apos; of the {3} element &apos;{4}&apos; and may not be compatible with the CLR type &apos;{5}&apos;..
        /// </summary>
        internal static string UserDefinedDbType {
            get {
                return ResourceManager.GetString("UserDefinedDbType", resourceCulture);
            }
        }
    }
}
