//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlMetal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlMetal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlMetal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calysto.SqlMetal.SqlMetal.Resources.SqlMetal", typeof(SqlMetal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output as source code. Cannot be used with /dbml option..
        /// </summary>
        internal static string CodeDescription {
            get {
                return ResourceManager.GetString("CodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /code[:file].
        /// </summary>
        internal static string CodeUsage {
            get {
                return ResourceManager.GetString("CodeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection string. Cannot be used with /server, /database, /user or /password options..
        /// </summary>
        internal static string ConnectionStringDescription {
            get {
                return ResourceManager.GetString("ConnectionStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /conn:&lt;connection string&gt;.
        /// </summary>
        internal static string ConnectionStringUsage {
            get {
                return ResourceManager.GetString("ConnectionStringUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of data context class (default: derived from database name)..
        /// </summary>
        internal static string ContextDescription {
            get {
                return ResourceManager.GetString("ContextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /context:&lt;type&gt;.
        /// </summary>
        internal static string ContextUsage {
            get {
                return ResourceManager.GetString("ContextUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) Microsoft Corporation. All rights reserved..
        /// </summary>
        internal static string CopyrightString {
            get {
                return ResourceManager.GetString("CopyrightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not identify primary key column &apos;{0}&apos; in table &apos;{1}&apos;..
        /// </summary>
        internal static string CouldNotIdentifyPrimaryKeyColumn {
            get {
                return ResourceManager.GetString("CouldNotIdentifyPrimaryKeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to make property name from association {0}..
        /// </summary>
        internal static string CouldNotMakePropertyNameForAssociation {
            get {
                return ResourceManager.GetString("CouldNotMakePropertyNameForAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1018: Database cannot be specified when a connection string is specified already..
        /// </summary>
        internal static string DatabaseAndConnectionConflict {
            get {
                return ResourceManager.GetString("DatabaseAndConnectionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database catalog on server..
        /// </summary>
        internal static string DatabaseDescription {
            get {
                return ResourceManager.GetString("DatabaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1011: An input file or a database must be specified..
        /// </summary>
        internal static string DatabaseIsNotSpecified {
            get {
                return ResourceManager.GetString("DatabaseIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /database:&lt;name&gt;.
        /// </summary>
        internal static string DatabaseUsage {
            get {
                return ResourceManager.GetString("DatabaseUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output as dbml. Cannot be used with /map option..
        /// </summary>
        internal static string DbmlDescription {
            get {
                return ResourceManager.GetString("DbmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1023: Either /dbml or /code may be specified, but not both..
        /// </summary>
        internal static string DbmlOrCodeNotBoth {
            get {
                return ResourceManager.GetString("DbmlOrCodeNotBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1022: Either /dbml or /map may be specified, but not both..
        /// </summary>
        internal static string DbmlOrMapNotBoth {
            get {
                return ResourceManager.GetString("DbmlOrMapNotBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /dbml[:file].
        /// </summary>
        internal static string DbmlUsage {
            get {
                return ResourceManager.GetString("DbmlUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create code from SqlServer:.
        /// </summary>
        internal static string DirectGenerationDescription {
            get {
                return ResourceManager.GetString("DirectGenerationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal /server:myserver /database:northwind /code:nwind.cs /namespace:nwind .
        /// </summary>
        internal static string DirectGenerationExample {
            get {
                return ResourceManager.GetString("DirectGenerationExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1009: The parameter of the command line option &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base class of entity classes in the generated code (default: entities have no base class)..
        /// </summary>
        internal static string EntityBaseDescription {
            get {
                return ResourceManager.GetString("EntityBaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /entitybase:&lt;type&gt;.
        /// </summary>
        internal static string EntityBaseUsage {
            get {
                return ResourceManager.GetString("EntityBaseUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate intermediate dbml file from SqlServer:.
        /// </summary>
        internal static string ExtractDbmlDescription {
            get {
                return ResourceManager.GetString("ExtractDbmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal /server:myserver /database:northwind /dbml:northwind.dbml /namespace:nwind.
        /// </summary>
        internal static string ExtractDbmlExample {
            get {
                return ResourceManager.GetString("ExtractDbmlExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate dbml from a SqlCE sdf file:.
        /// </summary>
        internal static string ExtractFromSdfDescription {
            get {
                return ResourceManager.GetString("ExtractFromSdfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal /dbml:northwind.dbml northwind.sdf.
        /// </summary>
        internal static string ExtractFromSdfExample {
            get {
                return ResourceManager.GetString("ExtractFromSdfExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate dbml from SqlExpress local server:.
        /// </summary>
        internal static string ExtractFromSqlExpressDescription {
            get {
                return ResourceManager.GetString("ExtractFromSqlExpressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal /server:.\sqlexpress /database:northwind /dbml:northwind.dbml.
        /// </summary>
        internal static string ExtractFromSqlExpressExample {
            get {
                return ResourceManager.GetString("ExtractFromSqlExpressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate dbml by using a connection string in the command line:.
        /// </summary>
        internal static string ExtractUsingConnectionStringDescription {
            get {
                return ResourceManager.GetString("ExtractUsingConnectionStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal /conn:&quot;server=&apos;myserver&apos;; database=&apos;northwind&apos;&quot; /dbml:northwind.dbml.
        /// </summary>
        internal static string ExtractUsingConnectionStringExample {
            get {
                return ResourceManager.GetString("ExtractUsingConnectionStringExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract database functions..
        /// </summary>
        internal static string FunctionDescription {
            get {
                return ResourceManager.GetString("FunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /functions.
        /// </summary>
        internal static string FunctionsUsage {
            get {
                return ResourceManager.GetString("FunctionsUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate code with external mapping from dbml:.
        /// </summary>
        internal static string GenerateFromDbmlDescription {
            get {
                return ResourceManager.GetString("GenerateFromDbmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal /code:nwind.cs /map:nwind.map northwind.dbml.
        /// </summary>
        internal static string GenerateFromDbmlExample {
            get {
                return ResourceManager.GetString("GenerateFromDbmlExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May be a SqlExpress mdf file, a SqlCE sdf file, or a dbml intermediate file..
        /// </summary>
        internal static string InputFileDescription {
            get {
                return ResourceManager.GetString("InputFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1003: Input file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string InputFileDoesNotExist {
            get {
                return ResourceManager.GetString("InputFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input file&gt;.
        /// </summary>
        internal static string InputFileUsage {
            get {
                return ResourceManager.GetString("InputFileUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1005: Timeout must be a non-negative integer. Current value is &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidTimeoutFormat {
            get {
                return ResourceManager.GetString("InvalidTimeoutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language for source code: VB or C# (default: derived from extension on code file name)..
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /language:&lt;language&gt;.
        /// </summary>
        internal static string LanguageUsage {
            get {
                return ResourceManager.GetString("LanguageUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate mapping file, not attributes. Cannot be used with /dbml option..
        /// </summary>
        internal static string MapDescription {
            get {
                return ResourceManager.GetString("MapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /map[:file].
        /// </summary>
        internal static string MapUsage {
            get {
                return ResourceManager.GetString("MapUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1024: /map must be used together with /code..
        /// </summary>
        internal static string MapWithoutCode {
            get {
                return ResourceManager.GetString("MapWithoutCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1004: Multiple input files are not allowed..
        /// </summary>
        internal static string MultipleInputFiles {
            get {
                return ResourceManager.GetString("MultipleInputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace of generated code (default: no namespace)..
        /// </summary>
        internal static string NamespaceDescription {
            get {
                return ResourceManager.GetString("NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /namespace:&lt;name&gt;.
        /// </summary>
        internal static string NamespaceUsage {
            get {
                return ResourceManager.GetString("NamespaceUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1007: There is an IO error and the output file &apos;{0}&apos; cannot be opened..
        /// </summary>
        internal static string OutputFileIOError {
            get {
                return ResourceManager.GetString("OutputFileIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1008: The output file name &apos;{0}&apos; has an invalid format..
        /// </summary>
        internal static string OutputFileNameFormatError {
            get {
                return ResourceManager.GetString("OutputFileNameFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLinq.
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1017: Password cannot be specified when a connection string is specified already..
        /// </summary>
        internal static string PasswordAndConnectionConflict {
            get {
                return ResourceManager.GetString("PasswordAndConnectionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login password (default: use Windows Authentication)..
        /// </summary>
        internal static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /password:&lt;password&gt;.
        /// </summary>
        internal static string PasswordUsage {
            get {
                return ResourceManager.GetString("PasswordUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically pluralize or singularize class and member names using English language rules..
        /// </summary>
        internal static string PluralizeDescription {
            get {
                return ResourceManager.GetString("PluralizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pluralize.
        /// </summary>
        internal static string PluralizeUsage {
            get {
                return ResourceManager.GetString("PluralizeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Generates code and mapping for the LINQ to SQL component of the .NET framework. SqlMetal can:.
        /// </summary>
        internal static string ProgramDescription0 {
            get {
                return ResourceManager.GetString("ProgramDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Generate source code and mapping attributes or a mapping file from a database..
        /// </summary>
        internal static string ProgramDescription1 {
            get {
                return ResourceManager.GetString("ProgramDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Generate an intermediate dbml file for customization from the database..
        /// </summary>
        internal static string ProgramDescription2 {
            get {
                return ResourceManager.GetString("ProgramDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Generate code and mapping attributes or mapping file from a dbml file..
        /// </summary>
        internal static string ProgramDescription3 {
            get {
                return ResourceManager.GetString("ProgramDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider type: SQLCompact, SQL2000, SQL2005, or SQL2008. (default: provider is determined at run time)..
        /// </summary>
        internal static string ProviderDescription {
            get {
                return ResourceManager.GetString("ProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open &apos;{0}&apos;. Provider &apos;{1}&apos; not installed..
        /// </summary>
        internal static string ProviderNotInstalled {
            get {
                return ResourceManager.GetString("ProviderNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /provider:&lt;type&gt;.
        /// </summary>
        internal static string ProviderUsage {
            get {
                return ResourceManager.GetString("ProviderUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate serializable classes: None or Unidirectional (default: None)..
        /// </summary>
        internal static string SerializationDescription {
            get {
                return ResourceManager.GetString("SerializationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /serialization:&lt;option&gt;.
        /// </summary>
        internal static string SerializationUsage {
            get {
                return ResourceManager.GetString("SerializationUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1015: Server cannot be specified when a connection string is specified already..
        /// </summary>
        internal static string ServerAndConnectionConflict {
            get {
                return ResourceManager.GetString("ServerAndConnectionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database server name..
        /// </summary>
        internal static string ServerDescription {
            get {
                return ResourceManager.GetString("ServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /server:&lt;name&gt;.
        /// </summary>
        internal static string ServerUsage {
            get {
                return ResourceManager.GetString("ServerUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1025: Unable to extract stored procedure &apos;{0}&apos; from SqlServer because parameter &apos;{1}&apos; is the unsupported DbType &apos;{2}&apos;..
        /// </summary>
        internal static string SprocParameterTypeNotSupported {
            get {
                return ResourceManager.GetString("SprocParameterTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1019: Unable to extract stored procedure &apos;{0}&apos; from SqlServer because its result set contains columns with the same name &apos;{1}&apos;..
        /// </summary>
        internal static string SprocResultColumnsHaveSameName {
            get {
                return ResourceManager.GetString("SprocResultColumnsHaveSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1020: Unable to extract stored procedure &apos;{0}&apos; from SqlServer because its result set contains multiple anonymous columns..
        /// </summary>
        internal static string SprocResultMultipleAnonymousColumns {
            get {
                return ResourceManager.GetString("SprocResultMultipleAnonymousColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract stored procedures..
        /// </summary>
        internal static string SprocsDescription {
            get {
                return ResourceManager.GetString("SprocsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sprocs.
        /// </summary>
        internal static string SprocsUsage {
            get {
                return ResourceManager.GetString("SprocsUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout value to use when SqlMetal accesses the database (default: 0 which means infinite)..
        /// </summary>
        internal static string TimeOutDescription {
            get {
                return ResourceManager.GetString("TimeOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1006: The value of timeout cannot be negative. Current value is &apos;{0}&apos;..
        /// </summary>
        internal static string TimeoutMustNotBeNegative {
            get {
                return ResourceManager.GetString("TimeoutMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /timeout:&lt;seconds&gt;.
        /// </summary>
        internal static string TimeOutUsage {
            get {
                return ResourceManager.GetString("TimeOutUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1021: Unable to extract column &apos;{0}&apos; of Table &apos;{1}&apos; from SqlServer because the column&apos;s DbType is a user-defined type (UDT). .
        /// </summary>
        internal static string UnableToExtractColumnBecauseOfUDT {
            get {
                return ResourceManager.GetString("UnableToExtractColumnBecauseOfUDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1014: Unable to extract function &apos;{0}&apos; from SqlServer. {1}.
        /// </summary>
        internal static string UnableToExtractFunction {
            get {
                return ResourceManager.GetString("UnableToExtractFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1014: Unable to extract stored procedure &apos;{0}&apos; from SqlServer. {1}.
        /// </summary>
        internal static string UnableToExtractSproc {
            get {
                return ResourceManager.GetString("UnableToExtractSproc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1012: Unable to extract table &apos;{0}&apos; from SqlServer. {1}.
        /// </summary>
        internal static string UnableToExtractTable {
            get {
                return ResourceManager.GetString("UnableToExtractTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1013: Unable to extract view &apos;{0}&apos; from SqlServer. {1}.
        /// </summary>
        internal static string UnableToExtractView {
            get {
                return ResourceManager.GetString("UnableToExtractView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1000: Unknown language: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownLanguage {
            get {
                return ResourceManager.GetString("UnknownLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1002: Unknown option &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownOption {
            get {
                return ResourceManager.GetString("UnknownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1022: Unknown provider type: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownProvider {
            get {
                return ResourceManager.GetString("UnknownProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1001: Unknown serialization mode: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownSerializationMode {
            get {
                return ResourceManager.GetString("UnknownSerializationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal [options] [&lt;input file&gt;].
        /// </summary>
        internal static string UsageHeader {
            get {
                return ResourceManager.GetString("UsageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string UsageOptions {
            get {
                return ResourceManager.GetString("UsageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1016: User cannot be specified when a connection string is specified already..
        /// </summary>
        internal static string UserAndConnectionConflict {
            get {
                return ResourceManager.GetString("UserAndConnectionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login user ID (default: use Windows Authentication)..
        /// </summary>
        internal static string UserDescription {
            get {
                return ResourceManager.GetString("UserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQM1010: User is missing when password is present..
        /// </summary>
        internal static string UserIsMissing {
            get {
                return ResourceManager.GetString("UserIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /user:&lt;name&gt;.
        /// </summary>
        internal static string UserUsage {
            get {
                return ResourceManager.GetString("UserUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft (R) Database Mapping Generator 2008 version {0}\nfor Microsoft (R) .NET Framework version {1}.
        /// </summary>
        internal static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract database views..
        /// </summary>
        internal static string ViewsDescription {
            get {
                return ResourceManager.GetString("ViewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /views.
        /// </summary>
        internal static string ViewsUsage {
            get {
                return ResourceManager.GetString("ViewsUsage", resourceCulture);
            }
        }
    }
}
