//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calysto.Genesis.UnitTests.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppMemberPicture
    {
    	/// <summary>
    	/// Column, PrimaryKey
    	/// </summary>
        public int AppMemberPictureID { get; set; }
    	/// <summary>
    	/// Column, Nullable
    	/// </summary>
        public Nullable<int> AppMemberID { get; set; }
    	/// <summary>
    	/// Column, Nullable
    	/// </summary>
        public Nullable<System.DateTime> InsertionDate { get; set; }
    	/// <summary>
    	/// Column, Nullable, Unicode, MaxLength(500)
    	/// </summary>
        public string FileName { get; set; }
    	/// <summary>
    	/// Column, Nullable, MaxLength(MAX)
    	/// </summary>
        public byte[] ImageData { get; set; }
    	/// <summary>
    	/// Column, Nullable, MaxLength(20)
    	/// </summary>
        public string ImageMimeType { get; set; }
    	/// <summary>
    	/// Column, Nullable, MaxLength(MAX)
    	/// </summary>
        public byte[] ThumbData { get; set; }
    	/// <summary>
    	/// Column, Nullable, MaxLength(20)
    	/// </summary>
        public string ThumbMimeType { get; set; }

    }
}
