//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calysto.Genesis.UnitTests.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppPermission
    {
    	/// <summary>
    	/// Column, PrimaryKey
    	/// </summary>
        public int AppPermissionID { get; set; }
    	/// <summary>
    	/// Column
    	/// </summary>
        public bool IsActive { get; set; }
    	/// <summary>
    	/// Column, Unicode, MaxLength(100)
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// Column, Nullable, Unicode, MaxLength(500)
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>
    	/// Column, Nullable, Unicode, MaxLength(50)
    	/// </summary>
        public string GroupName { get; set; }
    	/// <summary>
    	/// Column, Nullable
    	/// </summary>
        public Nullable<int> Ordinal { get; set; }
    
    }
}
